[sdl]
fullscreen=false
output=surface
autolock=false
[dosbox]
machine=svga_s3
memsize=16
[cpu]
core=normal
cputype=auto
cycles=fixed 12000
[mixer]
nosound=true
[sblaster]
sbtype=sbpro2
sbbase=220
irq=7
dma=1
[render]
aspect=false
scaler=normal2x
